import { makeStyles } from "@material-ui/core/styles";

export const styles = makeStyles((theme) => ({
  gridContainer: {
    flexDirection: "column",
    flexWrap: "nowrap",
    backgroundColor: "#FFFFFF",
    padding: "10px",
  },
  body: {
    alignItems: "center",
    justifyContent: "center",
    margin: 0,
  },
  image: {
    maxWidth: "70%",
    maxHeight: "70%",
    position: "relative",
    top: "10%",
    zIndex: "99",
  },
  heading: {
    display: " flex",
    justifyContent: "center",
    alignItems: " center",
    textAlign: " center",
    fontFamily: "Ubuntu",
    fontStyle: "bold",
    fontWeight: "450",
    fontSize: "38px",
    lineHeight: "68px",
    color: "Black",
    paddingTop: "40px",
  },
  tableHeading: {
    display: " flex",
    justifyContent: "center",
    alignItems: " center",
    textAlign: " center",
    fontFamily: "Ubuntu",
    fontStyle: "bold",
    fontWeight: "400",
    fontSize: "30px",
    lineHeight: "48px",
    color: "Black",
    paddingTop: "60px",
    paddingBottom: "30px",
  },
  totalAmount: {
    color: "Black",
    fontWeight: "bold",
    fontSize: "15px",
    borderRadius: "8px",
    fontFamily: "Ubuntu",
    fontStyle: "normal",
    textAlign: "center",
    border: "2px solid black",
    alignSelf: "flex-end",
    padding: "10px",
    width: "182px",
    margin: "10px 0px 10px 10px",
  },
  signature: {
    color: "Black",
    fontWeight: "bold",
    fontSize: "16px",
    marginTop: "7.3%",
    fontFamily: "Ubuntu",
    fontStyle: "normal",
    textAlign: "center",
    alignSelf: "flex-end",
    maxWidth: "32%",
    marginBottom: "20px",
    paddingBottom: "10px",
    position: "absolute",
    left: "65%",
    right: "0",
    bottom: "0",
  },
  managerText: {
    maxWidth: "36%",
    padding: "7px 0px 1px 0",
  },
  printButton: {
    "&:hover": {
      backgroundColor: "transparent !important",
    },
    textTransform: "none",
    color: "#808CA3",
    padding: 0,
    fontFamily: "Ubuntu",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: "14px",
    minWidth: "50px",
    height: "26px",
  },
  block: {
    display: "flex",
    flexDirection: "row-reverse",
    paddingTop: "140px",
  },
}));
